In [1]:
##Numpy tutorial

In [2]:
##it is always important to import numpy initially
import numpy as np

In [3]:
my_list=[1,2,3,4,5,6]


In [4]:
arr=np.array(my_list)

In [5]:
##to check the type of arr

In [6]:
type(arr)

numpy.ndarray

In [7]:
print(arr)

[1 2 3 4 5 6]


In [8]:
##to check dimension of arr
arr.shape

(6,)

In [11]:
print(arr)

[1 2 3 4 5 6]


In [15]:
arr

array([1, 2, 3, 4, 5, 6])

In [16]:
##multidimentional array

In [17]:
my_ls1=[1,2,3,4,5,6]
my_ls2=[1,3,5,7,9,11]
my_ls3=[2,4,6,8,10,12]


In [18]:
myarr=np.array([my_ls1,my_ls2,my_ls3])

In [19]:
myarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [20]:
print(myarr)

[[ 1  2  3  4  5  6]
 [ 1  3  5  7  9 11]
 [ 2  4  6  8 10 12]]


In [21]:
myarr.shape

(3, 6)

In [22]:
##array dimensions can be changed

In [23]:
myarr.reshape([6,3])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 1,  3,  5],
       [ 7,  9, 11],
       [ 2,  4,  6],
       [ 8, 10, 12]])

In [25]:
myarr.reshape([1,18])

array([[ 1,  2,  3,  4,  5,  6,  1,  3,  5,  7,  9, 11,  2,  4,  6,  8,
        10, 12]])

In [26]:
##indexing

##accessing array elements

In [27]:
myarr

array([[ 1,  2,  3,  4,  5,  6],
       [ 1,  3,  5,  7,  9, 11],
       [ 2,  4,  6,  8, 10, 12]])

In [29]:
myarr[1,3]

7

In [30]:
myarr[0:2,0:2]

array([[1, 2],
       [1, 3]])

In [31]:
myarr[1:,4:]

array([[ 9, 11],
       [10, 12]])

In [32]:
myarr[1,-0:-5]

array([1])

In [33]:
myarr[1]

array([ 1,  3,  5,  7,  9, 11])

In [38]:
myarr[-1,]

array([ 2,  4,  6,  8, 10, 12])

In [39]:
myarr[-2]

array([ 1,  3,  5,  7,  9, 11])

In [40]:
myarr[-0]

array([1, 2, 3, 4, 5, 6])

In [45]:
myarr[1:4,1:2]

array([[3],
       [4]])

In [46]:
myarr[1,1:5]

array([3, 5, 7, 9])

In [47]:
myarr[-1,]

array([ 2,  4,  6,  8, 10, 12])